serge-server/config/routes.rb
Rails.application.routes.draw do
  
  # trips and reservations routes
  resources :trips, only: [:index, :create, :update, :destroy]
  resources :trips, only: [:show] do
    resources :reservations, only: [:index, :create, :destroy]
  end
  resources :reservations, only: [:show, :update]
  resources :reservations, only: [:show] do
    resources :groups, only: [:create]
  end
  # user and auth routes
  resources :sessions, only: [:create, :show]
  resources :registrations, only: [:create]
  delete :logout, to: "sessions#logout"
  get :logged_in, to: "sessions#logged_in"
  root to: "static#home"
end

serge-server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

serge-server/app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  belongs_to :reservation
end

serge-server/app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :trip
  has_many :users, through: :groups
end

serge-server/app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :reservations
end

serge-server/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates_uniqueness_of :username
    validates_presence_of :email
    validates_uniqueness_of :email

    has_many :trips
    has_many :reservations, through: :groups
end

serge-server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

serge-server/app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
    extend ActiveSupport::Concern
  
    included do
      before_action :set_current_user
    end
  
    def set_current_user
      if session[:user_id]
        @current_user = User.find(session[:user_id])
      end
    end
  end
  

serge-server/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :create, :destroy]

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    render json: { status: 200 }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:user_id, :reservation_id)
    end
end

serge-server/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def create
      user = User.create!(
        username: params["user"]["username"],
        email: params["user"]["email"],
        password: params["user"]["password"],
        password_confirmation: params["user"]["password_confirmation"],
      )
  
      if user
        session[:user_id] = user.id
        render json: {
                 status: :created,
                 user: user,
               }
      else
        render json: { status: 500 }
      end
    end
  end
  
  

serge-server/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  include CurrentUserConcern

  before_action :set_reservation, only: [:show, :update, :destroy]

  # GET /reservations
  def index
    @reservations = Reservation.order(:date_and_time)
  end

  # GET /reservations/1
  def show
    render json: @reservation.to_json
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # POST /reservations
  def create
    @reservation = Reservation.new(reservation_params)

    if @reservation.save
      render json: @reservation, status: :created, location: @reservation 
    else
      render json: @reservation.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /reservations/1
  def update
    if @reservation.update(reservation_params)
      render json: @reservation, status: :ok, location: @reservation
    else
      render json: @reservation.errors, status: :unprocessable_entity
    end
  end

  # DELETE /reservations/1
  def destroy
    @reservation.destroy
    render json: { status: 200 }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:trip_id, :type, :cost, :date_and_time, :location, :nickname, :details, :is_paid)
    end
end

serge-server/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include CurrentUserConcern
  
    def create
      user = User.find_by(email: params["user"]["email"]).try(:authenticate, params["user"]["password"])
  
      if user
        session[:user_id] = user.id
        render json: {
          status: :created,
          logged_in: true,
          user: user,
        }
      else
        render json: { status: 401 }
      end
    end
  
    #checks to see if the current user is logged in or not
    def logged_in
      if @current_user
        render json: {
          logged_in: true,
          user: @current_user,
        }
      else
        render json: {
          logged_in: false,
        }
      end
    end
  
    def logout
      reset_session
      render json: {
        status: 200, logged_out: true
      }
    end
  end
  

serge-server/app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home
        render json: {status: "It's working"}
    end
end

serge-server/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  include CurrentUserConcern

  before_action :set_trip, :set_order, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # Here, get all the trips for one given user using @current_user from current_user_concern
  def index
    @trips = Trip.where(user_id: @current_user[:id])
    render json: @trips.to_json
  end

  # GET /trips/1
  def show
    render json: @trip.to_json(include: :reservations)
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # POST /trips
  def create
    @trip = Trip.new(trip_params)
    
      if @trip.save 
        render json: @trip, status: :created, location: @trip
      else
        render json: @trip.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /trips/1
  def update
      if @trip.update(trip_params)
        render json: @trip, status: :ok, location: @trip
      else
        render json: @trip.errors, status: :unprocessable_entity
      end
  end

  # DELETE /trips/1
  def destroy
    @trip.destroy
      render json: { status: 200 }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    def set_order
      @reservations = Trip.find(params[:id]).reservations.order(:date_and_time)
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.require(:trip).permit(:name, :start_date, :user_id)
    end
end

serge-server/app/helpers/application_helper.rb
module ApplicationHelper
end

serge-server/app/helpers/groups_helper.rb
module GroupsHelper
end

serge-server/app/helpers/reservations_helper.rb
module ReservationsHelper
end

serge-server/app/helpers/trips_helper.rb
module TripsHelper
end

serge-server/app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :reservation_id %>
    <%= form.text_field :reservation_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

serge-server/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

serge-server/app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Reservation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.user_id %></td>
        <td><%= group.reservation_id %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

serge-server/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

serge-server/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @group.user_id %>
</p>

<p>
  <strong>Reservation:</strong>
  <%= @group.reservation_id %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

serge-server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SergeAuthApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

serge-server/app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :trip_id %>
    <%= form.text_field :trip_id %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :date_and_time %>
    <%= form.datetime_select :date_and_time %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_field :details %>
  </div>

  <div class="field">
    <%= form.label :is_paid %>
    <%= form.check_box :is_paid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

serge-server/app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

serge-server/app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Trip</th>
      <th>Type</th>
      <th>Cost</th>
      <th>Date and time</th>
      <th>Location</th>
      <th>Nickname</th>
      <th>Details</th>
      <th>Is paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.trip_id %></td>
        <td><%= reservation.type %></td>
        <td><%= reservation.cost %></td>
        <td><%= reservation.date_and_time %></td>
        <td><%= reservation.location %></td>
        <td><%= reservation.nickname %></td>
        <td><%= reservation.details %></td>
        <td><%= reservation.is_paid %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

serge-server/app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

serge-server/app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trip:</strong>
  <%= @reservation.trip_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @reservation.type %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @reservation.cost %>
</p>

<p>
  <strong>Date and time:</strong>
  <%= @reservation.date_and_time %>
</p>

<p>
  <strong>Location:</strong>
  <%= @reservation.location %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @reservation.nickname %>
</p>

<p>
  <strong>Details:</strong>
  <%= @reservation.details %>
</p>

<p>
  <strong>Is paid:</strong>
  <%= @reservation.is_paid %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

serge-server/app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

serge-server/app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

serge-server/app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.name %></td>
        <td><%= trip.start_date %></td>
        <td><%= trip.user_id %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

serge-server/app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

serge-server/app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trip.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @trip.start_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @trip.user_id %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>